### ISSUE TITLE
Fix librarian dependency integration for download CLI

### ISSUE THREAD

**Issue by trytofly94** [trytofly94/book-tool#58]
## Problem Description

Two download CLI tests are failing due to librarian dependency integration issues:

- `test_books_command_success`
- `test_books_command_with_all_options`

## Error Details

The tests are failing with: `'DownloadResult' object has no attribute 'book'`

This appears to be a data structure mismatch between the expected and actual DownloadResult objects.

## Impact

- **Priority**: Low (external dependency)
- **Scope**: Book download functionality via librarian CLI
- **Core Impact**: None (ASIN lookup and file processing work independently)

## Suggested Fix

1. Review DownloadResult data structure definition
2. Update test mocks to match actual implementation
3. Verify librarian CLI integration works with current data structures
4. Add integration tests with actual librarian CLI if available

## Context

This was identified during comprehensive testing of core book-tool functionality. All core features (ASIN lookup, file validation, book processing) are working correctly.
